services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:3000
    environment:
      - WUD_DOMAIN=${WUD_DOMAIN}
      - WUD_AUTH_BASIC_ADMIN_USER=${WUD_AUTH_BASIC_ADMIN_USER}
      - WUD_AUTH_BASIC_ADMIN_HASH=${WUD_AUTH_BASIC_ADMIN_HASH}
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`${WUD_DOMAIN}`)"
      - "traefik.http.routers.wud.tls=true"
      - "traefik.http.routers.wud.service=wud-svc"
      - "traefik.http.services.wud-svc.loadbalancer.server.port=3000"
      - "traefik.http.routers.wud.tls.certresolver=letsencrypt"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
